/**
 * Admin system ID scheme (BR-8, BR-12, BR-17).
 *
 * Original formula in admin system (Java):
 *   receiveId = (millis + 2^56 * appIdx) * 10 + randomDigit
 *
 * The value 2^56 separates the "namespace" between application indexes so that IDs
 * generated by the PDT application (appIdx = 2) cannot collide with IDs
 * generated by the admin website (appIdx = 1).
 *
 * IMPORTANT: The result is always a `bigint`. Its value is far above Number.MAX_SAFE_INTEGER
 * (2^53), so it MUST NOT be converted to Number without loss of precision (BR-12).
 */

export const TWO_POW_56 = 1n << 56n

export interface IdParts {
  appIdx: number
  millis: number
  digit: number
}

export function assertAppIdx(appIdx: number): void {
  if (!Number.isInteger(appIdx) || appIdx < 0) {
    throw new Error(`appIdx harus berupa integer >= 0 (diterima: ${appIdx})`)
  }
}

/** Composes raw ID from its components (replicating Java formula). */
export function composeId(appIdx: number, millis: number, digit: number): bigint {
  assertAppIdx(appIdx)
  if (!Number.isInteger(millis) || millis < 0) {
    throw new Error(`millis harus berupa integer >= 0 (diterima: ${millis})`)
  }
  if (!Number.isInteger(digit) || digit < 0 || digit > 9) {
    throw new Error(`digit harus integer 0..9 (diterima: ${digit})`)
  }
  return (BigInt(millis) + TWO_POW_56 * BigInt(appIdx)) * 10n + BigInt(digit)
}

/** Decomposes ID into its components (used for verification & auditing). */
export function decomposeId(id: bigint): IdParts {
  const digit = Number(id % 10n)
  const base = id / 10n
  const appIdx = Number(base / TWO_POW_56)
  const millis = Number(base % TWO_POW_56)
  return { appIdx, millis, digit }
}

/** Smallest possible ID for a given appIdx (to narrow queries). */
export function minIdForApp(appIdx: number): bigint {
  assertAppIdx(appIdx)
  return TWO_POW_56 * BigInt(appIdx) * 10n
}

/** Largest possible ID for a given appIdx (1 namespace unit smaller than appIdx+1). */
export function maxIdForApp(appIdx: number): bigint {
  assertAppIdx(appIdx)
  return TWO_POW_56 * BigInt(appIdx + 1) * 10n - 1n
}

export type NowFn = () => number
export type RandomFn = () => number

/**
 * Concurrency-safe ID generator (multi-device writing to the same
 * server) guaranteed to be monotonically unique within a single process.
 *
 * The original Java implementation uses `synchronized` + `Thread.sleep` because IDs
 * are only guaranteed unique within a single JVM. Here we use a monotonic millis counter,
 * which is safe across multiple requests in the same process. Each instance
 * is assigned a distinct appIdx to partition the writer namespaces (BR-17).
 */
export class IdGenerator {
  private lastMillis: number

  constructor(
    private readonly appIdx: number,
    private readonly now: NowFn = Date.now,
    private readonly random: RandomFn = Math.random,
  ) {
    assertAppIdx(appIdx)
    this.lastMillis = now()
  }

  next(): bigint {
    let millis = this.now()
    // Ensure millis is strictly increasing so two sequential invocations
    // never produce the same ID even within the same clock millisecond.
    if (millis <= this.lastMillis) {
      millis = this.lastMillis + 1
    }
    this.lastMillis = millis
    const digit = Math.floor(this.random() * 10)
    return composeId(this.appIdx, millis, Math.min(9, Math.max(0, digit)))
  }

  /** Last millisecond value used (for debugging/audit). */
  get lastMillisUsed(): number {
    return this.lastMillis
  }
}

/** Always format/transport bigint as string (BR-12). */
export function idToString(id: bigint): string {
  return id.toString()
}
