/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverReceiveRouteImport } from './routes/over-receive'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as PosPurchaseIdRouteImport } from './routes/pos/$purchaseId'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as SessionsReviewSessionIdRouteImport } from './routes/sessions/review.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverReceiveRoute = OverReceiveRouteImport.update({
  id: '/over-receive',
  path: '/over-receive',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosPurchaseIdRoute = PosPurchaseIdRouteImport.update({
  id: '/pos/$purchaseId',
  path: '/pos/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsReviewSessionIdRoute = SessionsReviewSessionIdRouteImport.update({
  id: '/sessions/review/$sessionId',
  path: '/sessions/review/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/over-receive': typeof OverReceiveRoute
  '/settings': typeof SettingsRoute
  '/pos/$purchaseId': typeof PosPurchaseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/pos/': typeof PosIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/review/$sessionId': typeof SessionsReviewSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/over-receive': typeof OverReceiveRoute
  '/settings': typeof SettingsRoute
  '/pos/$purchaseId': typeof PosPurchaseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/pos': typeof PosIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/review/$sessionId': typeof SessionsReviewSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/over-receive': typeof OverReceiveRoute
  '/settings': typeof SettingsRoute
  '/pos/$purchaseId': typeof PosPurchaseIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/pos/': typeof PosIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/review/$sessionId': typeof SessionsReviewSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/over-receive'
    | '/settings'
    | '/pos/$purchaseId'
    | '/sessions/$sessionId'
    | '/pos/'
    | '/sessions/'
    | '/sessions/review/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/over-receive'
    | '/settings'
    | '/pos/$purchaseId'
    | '/sessions/$sessionId'
    | '/pos'
    | '/sessions'
    | '/sessions/review/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/login'
    | '/over-receive'
    | '/settings'
    | '/pos/$purchaseId'
    | '/sessions/$sessionId'
    | '/pos/'
    | '/sessions/'
    | '/sessions/review/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
  OverReceiveRoute: typeof OverReceiveRoute
  SettingsRoute: typeof SettingsRoute
  PosPurchaseIdRoute: typeof PosPurchaseIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  PosIndexRoute: typeof PosIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsReviewSessionIdRoute: typeof SessionsReviewSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-receive': {
      id: '/over-receive'
      path: '/over-receive'
      fullPath: '/over-receive'
      preLoaderRoute: typeof OverReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/$purchaseId': {
      id: '/pos/$purchaseId'
      path: '/pos/$purchaseId'
      fullPath: '/pos/$purchaseId'
      preLoaderRoute: typeof PosPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/review/$sessionId': {
      id: '/sessions/review/$sessionId'
      path: '/sessions/review/$sessionId'
      fullPath: '/sessions/review/$sessionId'
      preLoaderRoute: typeof SessionsReviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
  OverReceiveRoute: OverReceiveRoute,
  SettingsRoute: SettingsRoute,
  PosPurchaseIdRoute: PosPurchaseIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  PosIndexRoute: PosIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsReviewSessionIdRoute: SessionsReviewSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
